# Generated by Django 4.0.3 on 2022-05-05 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('litreview', '0002_userfollows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ticket',
            field=models.ForeignKey(blank=True, default='no ticket related', null=True, on_delete=django.db.models.deletion.CASCADE, to='litreview.ticket'),
        ),
    ]
